apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: github-security-scan
inputs:
  token:
    required: true
  language:
    required: false
    default: ''
  github-url:
    required: false
    default: '${{ cloudbees.scm.repositoryUrl }}'
  branch-name: 
    required: false
    default: '${{ cloudbees.scm.branch }}'
runs:
  using: composite
  steps:
    - id: run-orchestrator
      name: github-security-scan
      # latest image
      uses: docker://public.ecr.aws/l7o7z1g8/actions/github-security-sast-actions:main-666a3940b0ca2fe1bb09441c3d46ece72f792be6
      shell: bash
      env:
        CONFIG_JSON: '{\"metaInfo\":{\"url\":\"NA\",\"username\":\"NA\",\"password\":\"NA\",\"client_secret\":\"${{ inputs.token }}\",\"toolName\":\"githubsecurity\"},\"orchestratorInfo\":{\"language\":\"${{ inputs.language }}\",\"assetType\":\"CODE\",\"assetIdentifier\":\"${{ inputs.github-url }}\",\"profileIdentifier\":\"${{ inputs.branch-name }}\"},\"metaInformation\":{\"actor\":\"SCM-Bot\",\"commit_id\":\"${{ cloudbees.scm.sha }}\",\"scanner_type\":\"SAST\"}}'
        RUN_ID: ${{ cloudbees.run_id }}
        STEP_ID: ${{ step.internal.id }}
        JOB_ID: ${{ job.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{ step.internal.id }}"
        cd /
        /bin/bash -c "java -jar ./executables/github-security.jar & while ! nc -z localhost 5001; do sleep 1; done && ./executables/orchestrator -scanConfig \"${CONFIG_JSON}\" execute-analyser && exit"
