= CloudBees action: Scan with GitHub Advanced Security

Use this action to scan a public GitHub repository with the GitHub Advanced Security tool. GitHub Advanced Security can detect security vulnerabilities and coding errors in your code.

NOTE: Scanning of private GitHub repositories is not supported.

== Prerequisites

A Personal Access Token (PAT) with read-only permission is required to read the alerts from the public repository. This token is used in the YAML file, which pushes the alerts to CloudBees platform.

Configure the following steps for this action:

. Enable the alerts for your public repository.
. Create the PAT token.

=== Enable alerts

The *Dependabot*, *Code scanning*, and *Secret scanning* alerts must be enabled for the public repositories to identify vulnerabilities and coding errors.

To enable the alerts:

NOTE: User must have administrator access to the GitHub repository to enable permissions.

. Go to the GitHub repository.
. Select your profile from the top-right.
. Select menu:Settings[Security > Code security and analysis].
. In the *Dependabot* section, select *Enable* for the *Dependabot alerts* option.
. In the *Code scanning* section, select menu:Set up[Default] for the *CodeQL analysis* option under *Tools*.
. Select *Enable* for the *Secret scanning* option.

=== Create PAT token

A Personal Access Token (PAT), which is a 40 character hexadecimal value, is required to read the *Dependabot*, *Code scanning*, and *Secret scanning* alerts from public repository.

To create a PAT token, refer to these link:https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token[instructions].

[NOTE]
====
Consider the following when you create the PAT token:

* PAT token has read-only access for the *Dependabot*, *Code scanning*, and *Secret scanning* alerts.
* Repository for which the token is created has read-only access.
====

Use the created PAT token to invoke the action.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `token`
| String
| Yes
| The GitHub client secret.

| `language`
| String
| No
| The language of your Git repository code base.
Refer to the supported languages below.

| `github-url`
| String
| No
| The github url for the repository which needs to be scanned.

| `branch-name`
| String
| No
| The branch name for the repository which needs to be scanned.

|===

== Supported languages

[cols="1a,1a",options="header"]
.Supported languages with inputs
|===

| Supported language
| Input format

| Go
| `LANGUAGE_GO`

| Java
| `LANGUAGE_JAVA`

|===

== Usage example

In your YAML file, add:

[source,yaml]
----

      - name: Scan with GitHub Advanced Security
        uses: cloudbees-io/github-security-sast-scan-code@v1
        with:
          token: ${{ secrets.GITHUB_SECRET }}
          language: "LANGUAGE_JAVA"
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
